name: Build
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
     
    - name: Restore NuGet Packages
      run: nuget restore Foobar.sln
 
    - name: Build Lib
      run: msbuild Foobar.sln /p:Configuration=Release /p:Version=1.0.0 
   
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
       PROJECT_FILE_PATH: Foobar/Foobar.csproj
       VERSION_STATIC: 1.0.0
       PACKAGE_NAME: FoobarYoba
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
       NUGET_SOURCE: https://nuget.pkg.github.com/Barsik/index.json



      
  
    
   
