name: Build
 
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
      - uses: actions/checkout@v2

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        
      - name: xxx
        run: echo "xxx ${VERSION}"
        
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build and push
        run: echo "tag ${{ env.TAG }}"



      
  
    
   
