name: Build
 
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - id: qwe
    - name: Set VERSION variable from tag
    - run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}"
    - run: echo ${{ steps.qwe.VERSION }}
    - run: echo ${{ qwe.VERSION }}
    - run: echo ${{ VERSION }}
    
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1
 
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet Packages
      run: nuget restore Foobar.sln
 
    - name: Build Lib & pack
      run: msbuild Foobar/Foobar.csproj -t:Restore /p:Configuration=Release -t:pack /p:PackageVersion=2.0.0
      
    - name: Print  
      run: echo "Qwe ${{secrets.NUGET_API_KEY}}"
            
    - name: nuget push
      run: nuget push Foobar/bin/Release/Foobar.2.0.0.nupkg ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json
   



      
  
    
   
